### PR TITLE
SC-2099 - CD

### PR DESCRIPTION
**Pull request by dgcode**
* Added `cd` workflow for building the JS Bundle and deploying to AWS
* Removed `build/genie_bundle.js` as it will no longer be required

### CODE REVIEW

**Comment by DerivedClass** [comment]
@antoniobrandao - awaiting your review on this so it can be merged

**Comment by antoniobrandao** [comment]
@dgcode LGTM

**Comment by dgcode** [comment]
> @dgcode LGTM

@antoniobrandao are you happy for this to be merged given that the URL will need to be updated in the `shopif-app` repo?

**Comment by antoniobrandao** [comment]
@dgcode  sure. Do you plan to update the URL yourself? I can also merge and update the URL myself tomorrow

**Pull request merged**
